services:
  mc:
    image: itzg/minecraft-server:java21-graalvm
    ports:
      - 25575:25575
    environment:
      EULA: TRUE
      # server type
      TYPE: CURSEFORGE
      VERSION: 1.21.1
      CF_SERVER_MOD: Server-Files-2.17.zip
      REPLACE_ENV_DURING_SYNC: true
      # server settings
      DIFFICULTY: normal
      MAX_PLAYERS: 10
      VIEW_DISTANCE: 16
      SPAWN_PROTECTION: 0
      SERVER_NAME: giraffe
      MOTD: giraffes are cute uwu
      OPS: foxfirexo
      # fine-tuning
      MEMORY: 4G
      USE_AIKAR_FLAGS: true
      UID: ${UID:?missing}
      GID: ${GID:?missing}
    volumes:
      - ./data:/data
      - ./config:/config
      - ./mods:/mods
    tty: true
    stdin_open: true
    restart: unless-stopped
